monitor:
  mode: wide
topology:
  - name: sync1
    source:
      dbType: tibero
      ip: 192.168.1.187
      port: 4628
      connId: tibero
      connPwd: tmax
      proSyncUser: jsh_ott
      dbSid: tibero7_2
    target:
      dbType: oracle
      ip: 192.168.1.188
      port: 1525
      connId: JSH_OTT
      connPwd: jsh
      proSyncUser: jsh_tto
      dbSid: oraclesb
