monitor:
  mode: wide
  delay: 60000
topology:
  - name: TtoO_US_PROSYNC_I2G
    source:
      dbType: tibero
      ip: 192.168.1.187
      port: 4628
      connId: sys
      connPwd: tibero
      proSyncUser: US_PROSYNC_I2G
      dbSid: tibero7_2
    target:
      dbType: oracle
      ip: 192.168.1.188
      port: 1525
      connId: JSH_OTT
      connPwd: jsh
      proSyncUser: US_PROSYNC_I2G
      dbSid: oraclesb
