monitor:
  mode: wide
topology:
  - name: sync1
    mode: normal
    target1:
      db: tibero
      ip: 192.168.1.187
      port: 4628
      id: tibero
      pwd: tmax
      user: jsh_tto
      dbSid: tibero7_2
    target2:
      db: oracle
      ip: 192.168.1.213
      port: 1521
      id: JSH_OTT
      pwd: jsh
      user: jsh_ott
      dbSid: KIW
